import os

FLASK_APP = os.environ.get("FLASK_APP")
FLASK_DEBUG = os.environ.get("FLASK_DEBUG")
SQLALCHEMY_DATABASE_URI = os.environ.get('SQLALCHEMY_DATABASE_URI')
SQLALCHEMY_TRACK_MODIFICATIONS = False